<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="BubbleSort_tests.TestBubbleSort-20171101181542" skipped="0" tests="1" time="0.001">
	<testcase classname="BubbleSort_tests.TestBubbleSort" name="test_get_number_of_input" time="0.001">
		<error message="'BubbleSort' object has no attribute 'get_inputs_number'" type="AttributeError">
<![CDATA[Traceback (most recent call last):
  File "/home/asha/eclipse-workspace/MyApp/myappdev/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/asha/eclipse-workspace/MyApp/src/unittest/python/BubbleSort_tests.py", line 15, in test_get_number_of_input
    to_sort.get_inputs_number()
AttributeError: 'BubbleSort' object has no attribute 'get_inputs_number'

Stdout:
0
=============
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[0
=============
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
